# Form implementation generated from reading ui file 'ui/metadata_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MetadataWindow(object):
    def setupUi(self, MetadataWindow):
        MetadataWindow.setObjectName("MetadataWindow")
        MetadataWindow.resize(598, 323)
        self.gridLayout_2 = QtWidgets.QGridLayout(MetadataWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Row_01 = QtWidgets.QHBoxLayout()
        self.Row_01.setObjectName("Row_01")
        self.mdNumberAudiosLabel = QtWidgets.QLabel(parent=MetadataWindow)
        self.mdNumberAudiosLabel.setObjectName("mdNumberAudiosLabel")
        self.Row_01.addWidget(self.mdNumberAudiosLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.Row_01.addItem(spacerItem)
        self.mdApplyCancelBox = QtWidgets.QDialogButtonBox(parent=MetadataWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdApplyCancelBox.sizePolicy().hasHeightForWidth())
        self.mdApplyCancelBox.setSizePolicy(sizePolicy)
        self.mdApplyCancelBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.mdApplyCancelBox.setObjectName("mdApplyCancelBox")
        self.Row_01.addWidget(self.mdApplyCancelBox)
        self.gridLayout_2.addLayout(self.Row_01, 2, 0, 1, 1)
        self.mdScroll = QtWidgets.QScrollArea(parent=MetadataWindow)
        self.mdScroll.setWidgetResizable(True)
        self.mdScroll.setObjectName("mdScroll")
        self.mdScrollColumn = QtWidgets.QWidget()
        self.mdScrollColumn.setGeometry(QtCore.QRect(0, 0, 572, 255))
        self.mdScrollColumn.setObjectName("mdScrollColumn")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mdScrollColumn)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mdGrid = QtWidgets.QGridLayout()
        self.mdGrid.setObjectName("mdGrid")
        self.verticalLayout_2.addLayout(self.mdGrid)
        self.mdScroll.setWidget(self.mdScrollColumn)
        self.gridLayout_2.addWidget(self.mdScroll, 0, 0, 1, 1)

        self.retranslateUi(MetadataWindow)
        QtCore.QMetaObject.connectSlotsByName(MetadataWindow)

    def retranslateUi(self, MetadataWindow):
        _translate = QtCore.QCoreApplication.translate
        MetadataWindow.setWindowTitle(_translate("MetadataWindow", "Metadata Editor"))
        self.mdNumberAudiosLabel.setText(_translate("MetadataWindow", "36 songs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MetadataWindow = QtWidgets.QWidget()
    ui = Ui_MetadataWindow()
    ui.setupUi(MetadataWindow)
    MetadataWindow.show()
    sys.exit(app.exec())
