# Form implementation generated from reading ui file 'ui/metadata_row.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MetadataRow(object):
    def setupUi(self, MetadataRow):
        MetadataRow.setObjectName("MetadataRow")
        MetadataRow.resize(586, 299)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MetadataRow)
        self.horizontalLayout.setContentsMargins(0, 4, 0, 4)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.identifierLabel = QtWidgets.QLabel(parent=MetadataRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.identifierLabel.sizePolicy().hasHeightForWidth())
        self.identifierLabel.setSizePolicy(sizePolicy)
        self.identifierLabel.setObjectName("identifierLabel")
        self.horizontalLayout.addWidget(self.identifierLabel)
        self.VL_01 = QtWidgets.QFrame(parent=MetadataRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VL_01.sizePolicy().hasHeightForWidth())
        self.VL_01.setSizePolicy(sizePolicy)
        self.VL_01.setMaximumSize(QtCore.QSize(16777215, 20))
        self.VL_01.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.VL_01.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.VL_01.setObjectName("VL_01")
        self.horizontalLayout.addWidget(self.VL_01)
        self.titleLabel = QtWidgets.QLabel(parent=MetadataRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        self.titleInput = QtWidgets.QLineEdit(parent=MetadataRow)
        self.titleInput.setMaximumSize(QtCore.QSize(500, 16777215))
        self.titleInput.setObjectName("titleInput")
        self.horizontalLayout.addWidget(self.titleInput)
        self.VL_02 = QtWidgets.QFrame(parent=MetadataRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VL_02.sizePolicy().hasHeightForWidth())
        self.VL_02.setSizePolicy(sizePolicy)
        self.VL_02.setMaximumSize(QtCore.QSize(16777215, 20))
        self.VL_02.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.VL_02.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.VL_02.setObjectName("VL_02")
        self.horizontalLayout.addWidget(self.VL_02)
        self.artistLabel = QtWidgets.QLabel(parent=MetadataRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.artistLabel.sizePolicy().hasHeightForWidth())
        self.artistLabel.setSizePolicy(sizePolicy)
        self.artistLabel.setObjectName("artistLabel")
        self.horizontalLayout.addWidget(self.artistLabel)
        self.artistInput = QtWidgets.QLineEdit(parent=MetadataRow)
        self.artistInput.setMaximumSize(QtCore.QSize(500, 16777215))
        self.artistInput.setObjectName("artistInput")
        self.horizontalLayout.addWidget(self.artistInput)

        self.retranslateUi(MetadataRow)
        QtCore.QMetaObject.connectSlotsByName(MetadataRow)

    def retranslateUi(self, MetadataRow):
        _translate = QtCore.QCoreApplication.translate
        MetadataRow.setWindowTitle(_translate("MetadataRow", "MetadataRow"))
        self.identifierLabel.setText(_translate("MetadataRow", "Label"))
        self.titleLabel.setText(_translate("MetadataRow", "Title:"))
        self.artistLabel.setText(_translate("MetadataRow", "Artist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MetadataRow = QtWidgets.QWidget()
    ui = Ui_MetadataRow()
    ui.setupUi(MetadataRow)
    MetadataRow.show()
    sys.exit(app.exec())
